const PROFICIENCIES = [
  "Common",
  "Dwarvish",
  "Elvish",
  "Giant",
  "Gnomish",
  "Goblin",
  "Halfling",
  "Orc",
  "Abyssal",
  "Celestial",
  "Draconic",
  "Deep Speech",
  "Infernal",
  "Primordial",
  "Sylvan",
  "Undercommon",
  "Alchemist's Supplies",
  "Bagpipes",
  "Battleaxe",
  "Blowgun",
  "Brewer's Supplies",
  "Calligrapher's Supplies",
  "Carpenter's Tools",
  "Cartographer's Tools",
  "Club",
  "Cobbler's Tools",
  "Cook's Utensils",
  "Dagger",
  "Dart",
  "Dice Set",
  "Disguise Kit",
  "Dragonchess Set",
  "Drum",
  "Dulcimer",
  "Flail",
  "Flute",
  "Forgery Kit",
  "Glaive",
  "Glassblower's Tools",
  "Greataxe",
  "Greatclub",
  "Greatsword",
  "Halberd",
  "Hand Crossbow",
  "Handaxe",
  "Heavy Armor",
  "Heavy Crossbow",
  "Herbalism Kit",
  "Horn",
  "Improvised Weapon",
  "Javelin",
  "Jeweler's Tools",
  "Lance",
  "Land Vehicles",
  "Leatherworker's Tools",
  "Light Armor",
  "Light Crossbow",
  "Light Hammer",
  "Longbow",
  "Longsword",
  "Lute",
  "Lyre",
  "Mace",
  "Martial Weapons",
  "Mason's Tools",
  "Maul",
  "Medium Armor",
  "Morningstar",
  "Navigator's Tools",
  "Net",
  "Painter's Supplies",
  "Pan Flute",
  "Pike",
  "Playing Card Set",
  "Poisoner's kit",
  "Potter's Tools",
  "Quarterstaff",
  "Rapier",
  "Scimitar",
  "Shawm",
  "Shields",
  "Shortbow",
  "Shortsword",
  "Sickle",
  "Simple Weapons",
  "Sling",
  "Smith's Tools",
  "Spear",
  "Thieves' Tools",
  "Three-Dragon Ante Set",
  "Tinker's Tools",
  "Trident",
  "Unarmed Strike",
  "Viol",
  "War Pick",
  "Warhammer",
  "Water Vehicles",
  "Weaver's Tools",
  "Whip",
  "Woodcarver's Tools",
];

export default PROFICIENCIES;
